# Defines parameters for building and deploying.

# Location of the arrow-logo repository
location_arrow_logo = ~/projects/arrow-logo

# Location of the burakemir.github.io repository
location_deploy_prefix = /tmp
location_deploy = ${location_deploy_prefix}/burakemir.github.io

# Repository
repo = burakemir/burakemir.github.io.git

